# Generated by Django 4.0.3 on 2022-05-07 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.item')),
                ('equipped', models.BooleanField()),
                ('ac', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('app.item',),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.item')),
                ('equipped', models.BooleanField()),
                ('atk', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('app.item',),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_campaigns', to='app.profile')),
                ('players', models.ManyToManyField(to='app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Thorin Thabiticus', max_length=64)),
                ('level', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('hp', models.PositiveIntegerField()),
                ('hp_max', models.PositiveIntegerField()),
                ('strain', models.IntegerField(default=0)),
                ('atr_str', models.IntegerField()),
                ('atr_dex', models.IntegerField()),
                ('atr_con', models.IntegerField()),
                ('atr_int', models.IntegerField()),
                ('atr_wis', models.IntegerField()),
                ('atr_cha', models.IntegerField()),
                ('skl_admn', models.IntegerField()),
                ('skl_conn', models.IntegerField()),
                ('skl_conv', models.IntegerField()),
                ('skl_crft', models.IntegerField()),
                ('skl_exrt', models.IntegerField()),
                ('skl_heal', models.IntegerField()),
                ('skl_know', models.IntegerField()),
                ('skl_lead', models.IntegerField()),
                ('skl_magc', models.IntegerField()),
                ('skl_noti', models.IntegerField()),
                ('skl_perf', models.IntegerField()),
                ('skl_pray', models.IntegerField()),
                ('skl_pnch', models.IntegerField()),
                ('skl_ride', models.IntegerField()),
                ('skl_sail', models.IntegerField()),
                ('skl_shot', models.IntegerField()),
                ('skl_snek', models.IntegerField()),
                ('skl_stab', models.IntegerField()),
                ('skl_srvv', models.IntegerField()),
                ('skl_trde', models.IntegerField()),
                ('skl_work', models.IntegerField()),
                ('wealth', models.PositiveIntegerField()),
                ('background', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_backgrounds', to='app.background')),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='app.campaign')),
                ('foci', models.ManyToManyField(related_name='character_foci', to='app.focus')),
                ('items', models.ManyToManyField(related_name='character_items', to='app.item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
                ('spells', models.ManyToManyField(related_name='character_spells', to='app.spell')),
                ('vocation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_vocations', to='app.vocation')),
                ('armor', models.ManyToManyField(related_name='character_armor', to='app.armor')),
                ('weapons', models.ManyToManyField(related_name='character_weapons', to='app.weapon')),
            ],
        ),
    ]
