# Generated by Django 4.0.3 on 2022-05-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_inventoryitem_owner_alter_weapon_atk'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='equipable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='players',
            field=models.ManyToManyField(related_name='participant_campaigns', to='app.profile'),
        ),
        migrations.AlterField(
            model_name='character',
            name='foci',
            field=models.ManyToManyField(blank=True, related_name='character_foci', to='app.focus'),
        ),
        migrations.AlterField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(blank=True, related_name='character_spells', to='app.spell'),
        ),
    ]
