# Generated by Django 4.0.3 on 2022-05-10 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_item_equipable_alter_campaign_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocation',
            name='base_atk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='participant_campaigns', to='app.profile'),
        ),
        migrations.AlterField(
            model_name='character',
            name='ac',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='atr_cha',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='atr_con',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='atr_dex',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='atr_int',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='atr_str',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='atr_wis',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='app.campaign'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hp',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='hp_max',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='app.profile'),
        ),
        migrations.AlterField(
            model_name='character',
            name='wealth',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
