version: '3'

services:
  backend:
    build: ./services/backend
    ports:
      - 5000:5000
    volumes:
      - ./services/backend:/app
    user: 1000:1000
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000
