version: '3'

services:
  backend:
    build: ./services/backend
    ports:
      - 5000:5000
    volumes:
      - ./services/backend:/app
    user: 1000:1000
    command: python /app/src/manage.py runserver 0.0.0.0:5000
